# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c

# before_install: cd Example && pod install && cd -
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- xctool test -workspace Example/URBNShareKit.xcworkspace -scheme URBNShareKit-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
